version: "3.9"

services:
  pg-dados:
    image: postgres:15
    container_name: pg-dados
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    networks:
      - movieflix
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl-filmes:
    build: etl/.
    container_name: etl-filmes
    depends_on:
      pg-dados:
        condition: service_healthy
    env_file: .env
    restart: "no"
    networks:
      - movieflix


  app:
    build:
      context: ./app
    container_name: app
    env_file:
      - .env
    depends_on:
      etl-filmes:
        condition: service_completed_successfully
    networks:
      - movieflix
    expose:
      - "8000"
    
    
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - movieflix

networks:
  movieflix:
    driver: bridge
